title: ĞĞ¹ÑÑ‹Ğ»Ñƒ Ğ Ğ¾ÑÑĞ°Ñ…Ğ°Ñ†ĞºĞ°Ñ
description: |
  <img src="/portfolio/photo.jpeg" width="160" style="border-radius: 50%;"><br><br>
  Junior Data Analyst  
  Python Â· SQL Â· A/B Ñ‚ĞµÑÑ‚Ñ‹  

  <a href="/portfolio/resume.pdf" target="_blank">Ğ¡ĞºĞ°Ñ‡Ğ°Ñ‚ÑŒ Ñ€ĞµĞ·ÑĞ¼Ğµ</a><br>
  <a href="https://t.me/akataevva" target="_blank">Telegram: @akataevva</a><br>
  ğŸ“ +7 (982) 484â€‘01â€‘90<br>
  <a href="mailto:a.akataeva@yandex.ru">a.akataeva@yandex.ru</a><br>
  <a href="https://www.linkedin.com/in/a-rossakhatskaya/" target="_blank">LinkedIn</a><br>
  <a href="https://career.habr.com/rossakhatskaya" target="_blank">Habr Career</a>

theme: jekyll-theme-minimal
