title: ๐ฉโ๐ป ะะนััะปั ะะพััะฐัะฐัะบะฐั
description: |
  <img src="/portfolio/blob/main/photo.jpeg" width="120" style="border-radius: 50%;"><br>
  Junior Data Analyst  
  ๐ Python ยท SQL ยท A/B ัะตััั  
  <a href="/resume.pdf">๐ ะกะบะฐัะฐัั ัะตะทัะผะต</a><br>
  <a href="https://t.me/rshtsk" target="_blank">๐ฌ Telegram</a><br>
  <a href="mailto:aysylu@email.com">๐ง ะะฐะฟะธัะฐัั ะฝะฐ ะฟะพััั</a>

theme: jekyll-theme-minimal
